### ISSUE TITLE
Admin API Version compatibility

### ISSUE THREAD

**Issue by bossan** [Peter-Slump/python-keycloak-client#13]
The URLs used for the Admin API client are based on the URLS for Keycloak 3.3 and previous versions. Later versions have dropped the ``/admin`` part of the URL.
For example: ``/auth/admin/realms/{realm}/clients`` is ``/auth/realms/{realm}/clients`` for v3.4 and later.

To support later versions I would suggest setting these URLs conditionally based on the version.

**Comment by aberres** [comment]
I am running `4.8.3.Final` and `/admin` still seems to be needed.

The [docs](https://www.keycloak.org/docs-api/4.8/rest-api/index.html) mention a base path of `/auth` but without an additional `/admin` I get 404s.

From by POV it seems as if current Keycloak versions are supported.
