### ISSUE TITLE
How to create new REALM

### ISSUE THREAD

**Issue by ivanstefko** [Peter-Slump/python-keycloak-client#5]
Hi there, 
    according to documentation currently there is no ability to create new realm using python-kycloak-client... . So question is whether is there any workaround for it ... or do you plan in near feature add this functionality into python-keycloak-client? 

Thanks,

**Comment by Peter-Slump** [comment]
@ivanstefko I've currently no plans to add this functionality. However you are always welcome to contribute. 
As a workaround you can just add a new REALM using the Keycloak admin interface: https://www.keycloak.org/docs/latest/server_admin/index.html#_create-realm
