### ISSUE TITLE
Is this still under active development?

### ISSUE THREAD

**Issue by conor-nsurely** [Peter-Slump/python-keycloak-client#52]
Hey Peter,

We're looking to switch from our current library( 'python-keycloak') to an asynchronous one such as yours. Is this still under active development? And, if not are there any other projects you can recommend?

We're worried about compatibility issues with newer versions of Keycloak.

Thanks,
Conor

**Comment by predictap-droscoe** [comment]
@conor-nsurely I think this repo is basically abandoned, but the pypi project was taken over by this version which is alive and well: https://github.com/marcospereirampj/python-keycloak

**Comment by conor-nsurely** [comment]
Alright thanks for that!
